### ISSUE TITLE
credentialId in updateCredentialStatus may not fit all use cases

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/vc-api#126]
https://github.com/w3c-ccg/vc-http-api/pull/110 added the `updateCredentialStatus` operation which requires a caller to pass in a `credentialId` for updating a credential's status. This is a good start and I don't see an urgent problem with that, but wanted to point out that:

It's not quite clear if this field is meant to be the same as the `id` property of the VC, or if it can also be some internal reference that is not actually included in the VC itself.

- If it is the former, then it's important to keep in mind that `id` in a VC is optional, and that the API would therefore not support VCs that have a `credentialStatus` property but not an `id` property.
- If it is the latter, then there might be some edge cases where the entity that can change the status of a VC is not the same as the entity that originally issued it, and the internal reference needed for the API may not be available.

Also, perhaps in the future we will see more advanced credential status mechanisms (ZKP based?) where some piece of information other than a credential ID might be needed for changing the status.

Potential alternatives: 1. Pass the entire VC to the API for changing the status, 2. Pass the `credentialStatus` block of the VC to the API, 3. Pass some additional `options` to the API.

Like I said, not urgent, just wanted to capture these thoughts.

**Comment by msporny** [comment]
We discussed this on the 2022-03-29 call. @mkhraisha summarized the item. @mprorock noted that now that we have GET/PUT, seems like we added those things so we have clean/normal restful way to deal with this issue. @dlongley noted that it would be good to have a use case where a credential doesn't have an id that needs to be updated in this way. @mkhraisha asked if there would be a way to get credentials with no id. @dlongley said you could issue them, but might not be able to get them by id. @mprorock mentioned that we added GET so that you can always access a credential even if it doesn't have an ID via the /credentials/{id} pattern.

The discussion continues...

**Comment by nissimsan** [comment]
I would suggest giving this new value a more distinctive name such as `credentialRef`. 

`credentialId` versus `credential.id` are just too close, bound to cause confusion. 

(Irrespective of whether or not we end up going down the same path over on https://github.com/w3c-ccg/traceability-interop/issues/468).

**Comment by brownoxford** [comment]
Can you clarify where the returned `credentialId` property would live in the response to a `/credentials/issue` request? Would it be a sibling to `verifiableCredential`?

**Comment by msporny** [comment]
> Can you clarify where the returned `credentialId` property would live in the response to a `/credentials/issue` request? Would it be a sibling to `verifiableCredential`?

At present, it was suggested that it would be a sibling, but that sounds like a bad idea, doesn't it? :) 

@nissimsan's point also resonates with me.

We might want to put it in a container at the top level, much like the way DID Resolution returns its results:

https://w3c-ccg.github.io/did-resolution/#example-example-did-resolution-result

It uses the fields `didResolutionMetadata` and `didDocumentMetadata` ... so, perhaps we should have a field called `issuanceMetadata` that can then provide advisory information to the caller? So, the field would end up being `issuanceMetadata.<SOME_REFERENCE_ID>` ... thoughts?

**Comment by dlongley** [comment]
I made some comments [over here](https://github.com/w3c-ccg/traceability-interop/issues/468#issuecomment-1334171184) where I noted potential problems with having the issuing service auto-generate identifiers for referencing issued credentials. I think the better model is for the client to create and manage such identifiers, otherwise there doesn't seem to be a sensible way to resolve error cases.

**Comment by brownoxford** [comment]
@dlongley I am a fan of the idea that a "conflict" error can help identify whether or not VCs were issued in the case of a network (or similar) error. What are your thoughts on how to handle scenarios where issuers are not storing VCs (and therefore unable to identify conflicts).

**Comment by msporny** [comment]
The group discussed this on the 2024-01-16 call and determined that the PR that is raised should do the following things:

* Allow a client to specify an `id` property on the VC.
* Allow a client to NOT specify an `id` property on the VC, but provide an identifier that they can then use later to identify the issued VC specified via the `credentialId` option passed to the API.
* Allow VCs to be issued that do not have the `id` property set on the VC and do not have the `credentialId` option specified (for bearer-style VCs w/ no status information). Warn that there is no way to deal with duplicate errors (and maybe that's ok in some systems).
* Specify that the `credentialId` is not meant to be used as the `id` property on the VC.
* `credentialId` is an opaque value.
* Recommend against allow the server to auto-generate an `id` property on the VC (via a SHOULD NOT sentence) and warn that this can lead to unrecoverable partitioning errors (on a failed client call, you don't know what VC might have been created on the server). A client that's re-trying could create many VCs w/o knowing that they're creating many VCs due to a software error.
