### ISSUE TITLE
case 2 verifiable presentation has id IRI with two hash marks

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/vc-api#155]
In JSON-LD/RDF, nodes are identified by IRIs. Case 2 of the verifiable presentations contains an `id` with multiple `#` characters: https://github.com/w3c-ccg/vc-http-api/blob/master/packages/vc-http-api-test-server/__fixtures__/verifiablePresentations/case-2.json#L11

This is invalid in IRI syntax: https://tools.ietf.org/html/rfc3987#section-2.2

The test should therefore fail.

(I wonder, who added this test case in the first place, and why?!)

While looking into this, I found a message by @msporny from 2008 :) https://lists.w3.org/Archives/Public/public-rdf-in-xhtml-tf/2008Nov/0043.html

**Comment by msporny** [comment]
> Case 2 of the verifiable presentations contains an id with multiple # characters:

Oh, the dreaded "double-hash in a URI" Web corner case. :)

Another option here is to not put tests like this into the test suite... For example, is this an issuer test or a verifier test. There is an argument where it might be ok for an issuer to issue a VC with an invalid URI... but where the verifier should fail to verify the VC due to an invalid URI. There is also an argument here that the URIs should be opaque to the issuer and the verifier, and it's at a higher application layer that the URI should be checked. 

The concern here is performance. If we have to check every single URI for conformance when issuing/verifying, the performance impact could be significant in a large scale application. Many applications will just happily proceed with double hashes in URIs... it doesn't really have a negative effect in Linked Data land as most systems treat URIs as opaque and the job of the application layer to do validation. So, the question is -- what do we gain by rejecting invalid URIs with double fragments (and the answer, AFAICT hasn't changed in the last 12+ years... we lose "nothing").

So, options seem to be:

1. Issuer throws an error when detecting invalid URIs.
2. Verifier throws an error when detecting invalid URIs.
3. Both 1 and 2 above.
4. Issuer nor verifier throws an error (treat URIs as opaque)... let the application layer deal with it.
5. Provide a flag to the API to do "thorough syntax checking on all URIs" -- probably a bad idea.

There are good arguments for/against each one of the items above. :)

**Comment by clehner** [comment]
https://github.com/w3c-ccg/vc-api-test-suite/pull/3 replaced the test case to remove the double-hash.

Some relevant issues/discussion about handling of invalid IRIs in JSON-LD: https://github.com/w3c/json-ld-api/issues/517 https://github.com/w3c/json-ld-api/issues/533

**Comment by peacekeeper** [comment]
I agree this was fixed by https://github.com/w3c-ccg/vc-api-test-suite/pull/3, thanks @clehner for the reminder. Closing.
