### ISSUE TITLE
Support for scopes/rars in OAS3.0

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#219]
Work in progress here: https://gist.github.com/OR13/5c01814fb1cf929c4d0cc15ecca6a73d

**Comment by mavarley** [comment]
Just adding these references here; @jricher has added some issues to get RAR added to the OAS spec:

https://github.com/OAI/sig-security/issues/7

https://github.com/OAI/sig-security/issues/8

https://github.com/OAI/sig-security/issues/9

**Comment by msporny** [comment]
We discussed this on the 2022-05-17 call. @mavarley provided a background on the issue and noted the options being considered. @jricher provided background on RAR and why structured scopes is problematic when deployed -- structures lacking, new syntax/dimensions are problems -- RAR provides multi-dimensional structure for this sort of thing. Tooling is not available for RAR yet, @jricher is engaging w/ OAS group on adding it. Tooling can be adapted. @jricher feels like structured scopes is not a good idea given his experience. @mavarley wanted to consider how scopes, structured or otherwise, are used for exchanges -- allows variety of functionality w/ credentials and how credentials can be exchanged -- do we need nuanced scopes to support exchanges API (access token for one exchange, scoped for another exchange)? @msporny suggested that we accept PRs for test suites that support different authz mechanisms and proposals for how we integrate into the OAS files. @jricher noted that RAR is progressing on IETF track and is very close.

The group is currently looking for PRs on scopes, RARs, and ZCAPs and will review those PRs as they come in.

**Comment by msporny** [comment]
The group discussed this on the 2024-01-16 telecon and came to the conclusion that there isn't anyone in the current group that feels comfortable writing an adequate PR for this at this point in time. The group did agree that having examples in the future would be helpful. There are other PRs that will speak to authz and the group will raise new issues once those other authz PRs land if there is further need for examples for different authorization mechanisms.
