### ISSUE TITLE
Should the Issuer API allow authorization on a per credential subject granularity?

### ISSUE THREAD

**Issue by brianorwhatever** [w3c-ccg/vc-api#223]
As mentioned on the [mailing list](https://lists.w3.org/Archives/Public/public-credentials/2021Jul/0263.html) after further researching how RAR might be applied to the VC-HTTP-API it became evident it would allow us to remove some of the ambiguity over whether an action can be completed on a more fine grained level. Sure, an oauth `create:credential` scope might allow us to determine that the authorized user can create a VC but if we want to limit this any further it is going to require more business logic that could instead be included within the authz security itself.

I believe this is the core of what #40 is getting at and I think we should ask ourselves how granular we want authorization to be.

**Comment by msporny** [comment]
The group discussed this on 2022-09-06. @brianorwhatever noted that this was raised during the discussion about RARs/GNAP, etc. and the discussion has evolved since there. @dlongley noted that this discussion happened at a time where we had less clarity around API endpoints. We now have more clarity around what certain endpoints do. It might be more obvious now that having granularity around credentialSubject is of a lot of value. Seems like granularity is around exchanges and VC delivery. @brianorwhatever noted that this issue is deprecated at this point. @msporny noted that we have a design pattern that allows for hierarchical scopes if needed. @dlongley noted that new types of functionality could come along w/ a scope that enabled that functionality, that combined with a path, would give us a solution across GNAP/RAR/ZCAPs/OAuth2.

Given that the group has a design pattern that could be utilized across all known authz mechanisms that might be applied to the VC API, the group felt that it should close this issue and utilize the design pattern if such a use case came up in the future.
