### ISSUE TITLE
There should be a test for issue credential with a default issuer provided

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#274]
When `POST /credentials/issue` with  `{ credential: { issuer: did:example:123, ... }` => 200 IF AND ONLY IF `did:example:123` is the default issuer for the issuer implied by the configuration.

**Comment by OR13** [comment]
This is the default behavior today, but it would be good to have a test plan that was committed to source before attempting to write tests.

**Comment by msporny** [comment]
We discussed this on the 2022-10-25 call. @dlongley noted that issuer instances would already know what the issuer field should be. What was open to discussion was whether or not it was ok to include an `credential.issuer` field and it had to match between the configured issuer, or if it would be ignored. We also discussed whether issuer could be changed to another value, but @dlongley noted that might be a footgun. If you change the issuer, you will probably end up with something broken, so we should make it so you can't do that. The only reason we originally allowed what the issuer was is when we were building this API around a test suite instead of building it around actual use cases.
<strike>
The proposal is to disallow the setting `credential.issuer` to any value. It is assumed that the issuer endpoint will fill that value in when it is issuing a verifiable credential. We need to make sure that this won't conflict with what the Traceability API group is doing. /cc @OR13 @mprorock @mkhraisha @brownoxford 

If there are no objections, we should raise a PR that states that an error MUST be thrown if issuer is set when calling the issuer endpoint.

Next steps: Raise a PR that states that an error MUST be thrown if `credential.issuer` is set when calling the issuer endpoint.
</strike>

**Comment by dlongley** [comment]
The problem mentioned is that there are use cases for signing the same VC with multiple different proofs. It should be possible to hit issuer instance endpoint A to add an eddsa proof and then feed the verifiable credential result to issuer instance endpoint B to add an ecdsa proof (for example). Each proof would be from the same issuer, it would just use different cryptography to guard against any particular crypto failing and to improve interop / acceptance profiles.

**Comment by mkhraisha** [comment]
+1 to issuer must be either NOT set or set to the endpoints config.

**Comment by OR13** [comment]
> +1 to issuer must be either NOT set or set to the endpoints config.

-1 to an `or` here, I prefer a single requirement... removing optionality creates better interoperability.

**Comment by TallTed** [comment]
Think single server multi homing.

When a single service handles multiple issuer values, then client MUST set `issuer` to one of those.

When a single service only handles one issuer value, then client MAY set `issuer` to that value OR leave it unset.

Not all optionality is bad.

**Comment by OR13** [comment]
> When a single service handles multiple issuer values, then client MUST set issuer to one of those.

This is the case we support today... we currently treat `issuer` as required, because its much easier to reason about.

**Comment by msporny** [comment]
The group discussed this on 2023-06-13:

The group said that they don't want to prevent the use case described in this issue: to allow an endpoint to be configured to have multiple issuers. 

The configuration for the endpoint could:

* Have a default issuer that is used if none is specified by the client.
* Have multiple issuers that can be selected by the client (with or without a default if none is specified).

The group noted that this is highly dependent on the implementer and/or the deployment.

@OR13, the group couldn't make progress on this issue because they couldn't understand what you are asking for when you say "default". Default is never the only thing you can do, and your request seems to be asking for that. What do  you mean by "default" and "provided"?
