### ISSUE TITLE
Add language clarifying the security implications of the 'domain' property in DID Authentication

### ISSUE THREAD

**Issue by jandrieu** [w3c-ccg/vc-api#300]
We discussed the DID Auth PR https://github.com/w3c-ccg/vp-request-spec/pull/18, specifically the way in which a respondent to a DID Auth request should verify the `domain` before responding. 

Comments were made that different implementations have different mechanisms for doing so. For example, a CHAPI workflow checks the `origin` of the current web page[?] and requires that it match the `domain` in the request. 

Almost certainly, this check should be automated and not something that the user checks.

Let's document the meaning of the `domain` property expressed in terms that clarify these expected practices so processors of the request know what to do with its value.

**Comment by dlongley** [comment]
To respond to the inline question there about a CHAPI workflow:

In a CHAPI workflow, the `domain` value should be matched against the `credentialRequestOrigin` value in the credential request event received by the credential handler (i.e., digital wallet).

**Comment by msporny** [comment]
The group discussed this on the 2023-06-06 telecon. @jandrieu was present. 

There is now a section in the VP Request specification that covers the domain property in DID Authentication. That section can be found here: https://w3c-ccg.github.io/vp-request-spec/#did-authentication 

The group decided to close the issue because there is now at least one definition of DID Authentication (there may be others) and the request/response protocol and data model in the VPR specification.
