### ISSUE TITLE
Clarify expected use of "description" in "Initiate Exchange"

### ISSUE THREAD

**Issue by jrhender** [w3c-ccg/vc-api#330]
The [POST /exchanges/{exchange-id} endpoint](https://w3c-ccg.github.io/vc-api/#initiate-exchange) endpoint accepts the following schema:

| Property | Description |
| ------------- | ------------- |
| type | "object"  |
| description | "Data necessary to initiate the exchange."  |

My understanding is that "description" could be an object processed by the server to generate an appropriate `query` for the response.

Is this correct? Is the example below a correct use of initiate exchange?

### Example
to initiate an exchange about pizza 🍕 , one could do:

```http
POST /exchanges/pizza-review
Content-Type: application/json

{ 
     "type": "http://example.com/pizza-preferences/best-pizza-claim",
     "description": {
       "bestPizza": "neopolitan"  
     }
}
```

In response, the server could return:
```http
HTTP/1.1 201 Created

{
  "verifiablePresentationRequest": {
    "query": [{
        "type": "QueryByExample",
        "credentialQuery": {
          "reason": "We need your pizza taster credentials to see if you can make a claim about which pizza is best",
          "example": {
            "@context": [
              "https://www.w3.org/2018/credentials/v1",
              "http://example.com/pizza-preferences/"
            ],
            "type": "PizzaTasterCredential"
          }
        }
      }],
    "challenge": "3182bdea-63d9-11ea-b6de-3b7c1404d57f",
    "interact": {
      "service": [{
        "type": "UnmediatedPresentationService2021",
        "serviceEndpoint": "https://example.com/exchanges/pizza-review/0bc42ece-89f7-11ec-9af0-136dfa9e4dbb"
      }]
    }
  }
}
```

**Comment by dlongley** [comment]
I think this has a evolved with the introduction of configurations and instances, but the features are quite similar.

The concept of "exchangers" has been introduced (but needs to make its way into spec text), where a particular "exchanger" is used to create new exchanges. Additionally, control over creating particular exchanges is in the hands of an authorized party instead of an unauthorized one, e.g., it comes from the issuer coordinator.

The creation of an exchange is still expected to be "triggered" by some client on the issuer coordinator's website in many cases. To enable this, the issuer coordinator website exposes some interface to accept whatever input is desirable from a client. For example, a request that includes the above payload with best pizza claim information. This is not part of the VC API, but custom to the issuer coordinator.

From there, the issuer coordinator would create an exchange by making an authorized post to `/exchangers/pizza-review` (noting "exchangers" not "exchanges" in that URL). The payload would include whatever information is required to, for example, populate variables for a "best pizza claim" credential template that was previously configured and set up with the "pizza-review" exchanger. The result of creating this exchange would be an exchange URL that could be given to the client that is interacting with the issuer coordinator website.

There are a number of ways to communicate that exchange URL to the client. For example, it could be handed over via CHAPI, to a digital wallet that could complete the exchange. The issuer coordinator could include a VPR along with the exchange URL if the communication mechanism allows for it.

To initiate the exchange, the client (usually a digital wallet now) posts to the exchange URL with a payload that either includes a VP as a response to the VPR (if one was given) or an empty post body. The former will cause the exchange to proceed to the next step. Many exchanges are expected to have only one step -- that will result in returning a VP that contains, e.g., a pizza review VC. The latter (posting an empty body) can cause the exchange to respond with a VPR (if required) or with a VP (with e.g., a pizza review VC) if no additional input is needed to complete the exchange.

This approach allows for VPRs to be sent early in protocols that support it (saving a network call) but also allows for the VPR to be sent directly from the exchange endpoint if there isn't another way to communicate the VPR previously. This covers two known cases today:

1. VPRs can be sent via CHAPI to Web-based digital wallets that are able to receive CHAPI requests via browser "events".
2. VPRs can be too large to send in protocol initiation URLs such as those used for OID4VCI or native digital wallet applications generally, so they must be sent from within the exchange protocol itself.

**Comment by dlongley** [comment]
### New Example
to initiate an exchange about pizza 🍕 , one could do:

```http
POST /issuer-coordinator-website/custom/pizza-review
Content-Type: application/json

{ 
  "type": "http://example.com/pizza-preferences/best-pizza-claim",
  "description": {
    "bestPizza": "neopolitan"  
  }
}
```

The issuer coordinator would process this payload and send a request to an exchanger service to create a pizza-review exchange:

```http
POST /exchangers/pizza-review/exchanges
Content-Type: application/json

{ 
  "ttl": 900000,
  "variables": {
    "credentialId": "urn:uuid:3eef453a-5018-401a-ad53-cfe206ce272a",
    "description": {
      "bestPizza": "neopolitan"  
    }
  }
}
```

In response, the exchanger service could return:
```http
HTTP/1.1 204 Created
Location: /exchangers/pizza-review/exchanges/z32137y123812731287313ds
```

The issuer coordinator would send the full exchange URL and, optionally, a VPR over CHAPI (or other protocol) to the client.

Then, the client would post to that full URL as described above.

**Comment by msporny** [comment]
The group discussed this on the 2023-06-27 telecon:

@dlongley Noted that this has changed slightly since instances were created. There was a concern that anyone could hit exchanges, but since there are configurations/instances now, we've introduced concept of exchangers and the idea there is that only authorized party can create an exchange (doesn't change what features are available based on example above). Issuer Coordinator is most common client of using exchanger service, would have created a previous exchanger (pizza review) plus templates for exchanges. If an issuer came to Issuer Coordinator website, they could accept whatever data they wanted, whatever data payload they have in spec, and in accepting whatever data from user's client, if it's valid, could have user authentication, they could say "data user sent me is valid, can create exchange" -- would hit pizza review exchanger, put new variables into exchange, variables could include credential ID, could include input from user such as what they thought best pizza was, and they send it over to exchanger service, create new exchange with certain variables, exchanger instance is created, exchanger URL is provided back to the client. How you get exchange URL over to client's digital wallet is out of scope for spec (but could go into CHAPI request, for example). If someone has a CHAPI-based wallet, exchange URL is provided to wallet, and exchange URL is used by wallet to initiate VC API Exchanges.

@jrhender noted that he liked the direction this was going. Energy Web has something similar to what @dlongley describes above. Via HTTP POST, they create an exchange and that's done by an authorized component (by Issuer Coordinator). +1 to this if understood correctly. Question: On returning the VPR, Initiate exchange could return VPR as a whole or URL to continue the exchange? @dlongley noted that there are two different pieces -- piece where exchange is already created, that would return URL to use exchange. We could enable also sending VPR at same time -- could talk about that more, perhaps assumed that issuer coordinator would know what VPR to send to client to go along w/ exchange. Creation of exchange done by authorized party, then exchange URL to do exchange -- POST empty body to exchange URL and get back response from exchange, if the exchange needs information from you, it would be a VPR, otherwise, delivery of credentials. If you POST empty body, if issuer coordinator knew what VPR would be for exchange, could send it along w/ exchange URL. Looking at CHAPI request - could include endpoint AND VPR in the request at once. If Digital Wallet accepts all data at once, you could already have VPR and respond immediately w/o empty post.

However, you have to (in some protocols like OID4) you can't include all of that in a URL. The same is true in interating w/ native apps in CHAPI. Native Apps can only use a URL, can't use rich data -- too large, VPR is too big to send over protocols in wallet selection (like OID4).

@dlongley noted that we have other issues for adding exchanges to the spec. @jrhender wondered if renaming from "initiate" to "create exchange" would better capture what we're talking about? @dlongley noted that we need a URL for creating an exchange, can't just rename the endpoint, would change /exchangers/SOME_NAME/exchanges (would be posted to create an exchange) -- at that point, the rest of this fits. How would the response change, create an exchange at that point, but not using it yet. Party creating the exchange is not the party using the exchange (that's a concept we'd want to capture as well).

@PatStLouis wondered where the VPR is coming from... how does the server know which VPR to include in the request? Is it dependent on input or dependent on instance configuration? @jrhender noted that it's coming from variables in POST body -- TTL property, variables, that's what's being used to know which VPR would be returned upon exchange being hit. @msporny noted that we might not be able to define the configuration languages, template languages, and variable languages in the first iteration of the spec and might need to delegate that to the implementer documentation.

@jrhender noted that it's not clear if this is the highest priority to standardize. There might need to be less interop between coordinators and services, might be lower priority on doing something here. 

The group suggested that they will process other "ready for PR" issues that have to do with exchanges and once those PRs have been processed, we'll come back around to this issue to see what remains to be done.

**Comment by msporny** [comment]
The group discussed this on the 2024-02-27 call and decided to close the issue because they felt that issues #338 and #267 would resolve this issue in time.
