### ISSUE TITLE
What option specifies curve type (P-256, P-384) for ecdsa-rdfc-2019 issuer?

### ISSUE THREAD

**Issue by filip26** [w3c-ccg/vc-api#368]
looking at [options object](https://w3c-ccg.github.io/vc-api/#issue-credential) there is no such property

**Comment by msporny** [comment]
At present, the consensus in the group seems to be that the issuance endpoint is configured (out of band) to use a particular curve type and key size. That is, the issuer endpoint instance is pre-configured with a variety of things such as curve type, key size, and status list mechanism... the client is not expected to set any of those things.

Implementations may provide an implementation-specific option to switch between those things, but the specification won't provide those sorts of guidance since the specification just establishes the baseline of what's expected for implementations and not all of the implementation-specific options that can exist.

**Comment by filip26** [comment]
I understand that this request is resolved as out of scope, but given the fact that this specification just lists bunch of endpoints and parameters ... to define "a baseline of what's  expected" in terms of what HTTP requests you can make. Wouldn't a recommendation on how to implement custom parameter be a great addition?

**Comment by msporny** [comment]
The group discussed this on the 2024-02-27:

@dlongley noted that the client should probably not specify the curve type, should specify a reference to the public key instead. Specifying anything other than a key can be abused, bad security practice -- it is expected that a client will be handed an endpoint that has a valid backing configuration (including key to use for signing and all of its relevant metadata). Having a client request a key to use based on parameters can result in a failure to issue/sign and could lead to security issues if a server were to try to comply. 

@filip26 said:
> Wouldn't a recommendation on how to implement custom parameters be a great addition?

Yes, and that is being handled via PR #370.
