### ISSUE TITLE
Remove public-facing API calls

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/vc-api#40]
This is meant to be an internal API used to integrate VC issuing capabilities with an existing backend system such as CRM, etc. This should not contain any operations for interacting directly with a VC Holder. The API however does currently contain two such operations:

- `GET` on `/credential/{credentialReference}/status`: Retrieves the credential status and returns it in the response body.
- `POST` on `/credential/{credentialReference}/refresh`: Refreshes a credential and returns it in the response body.

These should be removed.

**Comment by OR13** [comment]
This issue is stale, and has already been implemented.... this issue should be closed.

**Comment by msporny** [comment]
This was discussed on the 2021-07-27 call.

Comments made included:

* In general, there should be authorization on every endpoint.
* Internal vs. external is not a good indicator of anything.
* We need a better description related to what this issue is getting at and are leaving this issue open until either 1) the original issuer submitter opens a new, more specific issue, or 2) 30 days elapse, at which point the issue will be closed.

**Comment by msporny** [comment]
> 30 days elapse, at which point the issue will be closed.

This has happened, closing.
