### ISSUE TITLE
need to distinguish cred-issuer relationship in URI namespace?

### ISSUE THREAD

**Issue by dhh1128** [w3c-ccg/vc-api#45]
Today, most credential workflows are simple. We assume a person (not an institution or IoT thing, usually) shows up at an issuer's API and an issue-the-credential workflow immediately begins. Thus, we think that /credentials is a reasonable place to put all credentials related to an issuer, and that all credentials under that namespace are *issued* or *about-to-be-issued* or *previously-issued* credentials.

But in the future, what if the interaction between an issuer and a potential holder is not so simple? What if, for example, the potential holder asks the issuer to prove something before the issuance, and/or what if the issuer asks the potential holder to prove something? In such a case, other types of credentials become relevant:

* credentials held by the issuer, and possibly used to provide assurance to the potential holder
* credentials presented by the potential holder to the issuer (the issuer temporarily becomes a verifier)

Because of this, I think it's unwise to assume that everything under /credentials is a credential that the issuer is responsible for creating. We may want /credentials/issued and /credentials/held and /credentials/received, for example. Or we may want to use a query string to split the semantics up. Or something similar. I don't have a strong opinion I'm advocating about how to do it--I'm only trying to get us to think about how the same party can play multiple roles, such that the URI namespaces need to be combinable without creating conflicts.

**Comment by David-Chadwick** [comment]
+1

Very good points Daniel

**Comment by bumblefudge** [comment]
Conversation continues in issue of broken-out use-case repo above! ^

**Comment by msporny** [comment]
The VCAPI group discussed this today and would like to gather a concrete use case that is related to this issue.

We also mentioned that the way GNAP is architected might have relevance to this issue.

We also discussed that perhaps the API already supports this viewpoint because any server can play any combination of issuer/verifier/holder roles by exposing the HTTP API endpoints on itself.

**Comment by dhh1128** [comment]
>We also discussed that perhaps the API already supports this viewpoint because any server can play any combination of issuer/verifier/holder roles by exposing the HTTP API endpoints on itself.

I feel like this misses the point. Of course any entity can play any role. But will the URL namespace `/credentials` -- which made sense under the simplistic assumption that all nouns it subsumes are items that a server is going to issue -- still make sense when the server is a holder? Do we want to encourage people to think that it's a good idea to reach into a holder's treasure chest of credentials and GET them at will?

What I'm claiming is that the semantics of held credentials are different from the semantics of issued credentials (or of received credentials, where the server acted as verifier). They have radically different operations and security properties. So it might be smart to separate the `/credentials` URL namespace in the API by role. We don't want to expose a single enumeration that covers all three types; it's a recipe for security problems and user confusion.

**Comment by msporny** [comment]
> What I'm claiming is that the semantics of held credentials are different from the semantics of issued credentials (or of received credentials, where the server acted as verifier).

Please take a look at the current API, where we separate things by "thing you're trying to do", like issuing, verifying, and presenting:

https://w3c-ccg.github.io/vc-api/#issuing
https://w3c-ccg.github.io/vc-api/#verifying
https://w3c-ccg.github.io/vc-api/#presenting

I get your point - held credentials are different from issued credentials -- and I don't think the group is deeply committed to the names of the paths... we're more focused on the functionality. 

It was hard to process this issue on the call today because there was no concrete action other than "think about it"... which is maybe ok for an issue at this point in the VC APIs lifecycle... but we're going to increasingly get pressured into "Ok, so what do we do about this issue?" and without something to march towards, the conversation will turn to closing the issue because there is no concrete ask of the group. I expect we're months away from that happening... we have 89 issues to process and can only do about 6-8 of them per call... so it'll be a while before we get back around to this issue. Hopefully, people will engage here to suggest some concrete changes to the API that address the concerns raised in this issue.

**Comment by TallTed** [comment]
Why should we be dictating `/credentials` namespace at all?  Without getting into the i18n issues, I still wonder why `/creds`, `/certs`, `/thingies` wouldn't be just as valid... and if they are, whether we need to dictate what namespaces should (must? may?) be used for what purpose by what rolefiller...

**Comment by dhh1128** [comment]
I think this issue has accomplished its purpose in that it has triggered some thoughtful discussion. From my perspective, it can be closed.

**Comment by msporny** [comment]
> I think this issue has accomplished its purpose in that it has triggered some thoughtful discussion. From my perspective, it can be closed.

Ok, thanks -- marking this as pending close. The issue will be closed in 7 days unless there are objections.
