### ISSUE TITLE
Architectural Model Discussion

### ISSUE THREAD

**Issue by David-Chadwick** [w3c-ccg/vc-api#54]
This issue replaces w3c-ccg/vc-http-api#53 (which requested the architectural model be published) with discussions about the architectural model that has now been published. Here are my comments on the published model.

1. Dotted communcation 12. The verifier should **never** communicate with the issuer. This is in direct contradiction with the VC Data Model. This communciation channel should be removed.

2. The Application Services component is too large and too vague. It should be split into two components, namely, The Issuer Application, and The VC Issuer i.e. you need to draw a line through the middle of the existing Application Services component. The top half, the Issuer Application will talk to the UserAgent/browser as now and the bottom half, the VC Issuer, will talk to the Wallet/Holder as now. Both will communicate with the Subject Database.

3. The internal APIs that you need are 

i) between the Issuer Application and the VC Issuer. Your existing API is this interface
ii) between the above two and the Subject Database.

4. If you think it is desirable to compartmentalise the VC Issuer into standardised components then you might wish to specify APIs between the VC Issuer and the Resolver, Credential Store and Vault etc.

**Comment by peacekeeper** [comment]
We discussed this on the [05 Oct VC API Work Item call](https://w3c-ccg.github.io/meetings/2021-10-05-vchttpapi/), and came to the conclusion that 1. by now there is an architecture diagram in the repository, which means that the original intent of this issue is resolved, and 2. @jandrieu has recently been working on a sequence diagram and will work on a PR to incorporate that into the repo.

**Comment by msporny** [comment]
An architectural diagram now exists in the current spec, closing.
