### ISSUE TITLE
Default verificationMethod option

### ISSUE THREAD

**Issue by clehner** [w3c-ccg/vc-api#67]
The description for `verificationMethod` in `LinkedDataProofOptions` says:

> The URI of the verificationMethod used for the proof. If omitted a default assertionMethod will be used.

https://github.com/w3c-ccg/vc-http-api/blob/master/docs/vc-http-api.yml#L153

I am surprised that it mentions assertionMethod there. Should it instead say "If omitted a default verificationMethod will be used"? But what would be a default verificationMethod anyway? Some URL that the HTTP server is configured to use?

Edit: should the VC issuer or VP holder property be used as a default verificationMethod, or to derive one?

**Comment by peacekeeper** [comment]
Files have changed a bit in the meantime.

Link to the original content line:
https://github.com/w3c-ccg/vc-api/blob/886ab06d57d1021037fa0d8aa735ac41218c4c21/docs/vc-http-api.yml#L153

Link to (I think) corresponding current content line:
https://github.com/w3c-ccg/vc-api/blob/main/components/IssueCredentialOptions.yml#L25

Last content change was in https://github.com/w3c-ccg/vc-api/commit/428ec4ac.

**Comment by peacekeeper** [comment]
And yes I agree that this should say "default verificationMethod" instead of "default assertionMethod".

> But what would be a default verificationMethod anyway?

Good question, I have some ideas about that:

* As you suggest, I think it should be derived from the VC issuer or VP holder, which in many cases (but not necessarily) are DIDs.
* Some DIDs only have a single verificationMethod (with the "assertionMethod" verification relationship), then this is the default.
* Some DIDs may have multiple verificationMethods, but the DID method could define which one is default.
* It could depend on the configuration of the Issuer software (but this could lead to vendor lock-in, since the behavior would be inconsistent between implementations).

**Comment by clehner** [comment]
Thanks @peacekeeper, that makes sense.

**Comment by msporny** [comment]
Fixed in https://github.com/w3c-ccg/vc-api/pull/248, closing.
