### ISSUE TITLE
Need a mechanism to verify multiple certificates attached to an agricultural shipment 

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/vc-api#88]
When processing a shipment of agricultural goods, multiple VCs (sharing a common parent type) need to be verified with a single request for each item type and packaging material (e.g. there will be multiple certificates attached to one shipping container of blueberries).  How is this best approached with the api?

**Comment by mprorock** [comment]
@OR13 any thoughts on how you have approached multiple verifications in the past?

**Comment by OR13** [comment]
@mprorock we talked about this in the previous phase. 

Its possible to make a verifiable presentation which contains no proof, and multiple credentials... (its basically a stanard bucket of credentials with no replay attack prevention).

in order to keep the api simple I would recommend that approach.... however if folks want the `verifyPresentation` api operation to REQUIRE a proof.... this won't work and we would need another endpoint like `verifyCredential` that could do multiple at once.

**Comment by OR13** [comment]
It looks like todays APIs require `proof`.... https://w3c-ccg.github.io/vc-http-api/#/Verifier/verifyPresentation

so the options are:

1. overload verifyPresentation to allow verification of presentations that have no proof.
2. create `verifyCredentials` which can check multiple credentials at once.

@dlongley any preference here?

**Comment by bumblefudge** [comment]
The supply-chain sub-cohort discussion group discussed this today. All of us support an extension to the API in time for the next plugathon. We had no strong objections to 1 OR 2, but have a slight preference for 2 since it minimizes the chance of breaking changes for any existing implementations.

**Comment by dlongley** [comment]
It seems like providing an option to `verifyPresentation` that would not reject presentations lacking a proof is simpler than creating an entirely separate API that does the same thing. My vote would be for #1.

**Comment by OR13** [comment]
This was solved when we enabled verifying presentations without proofs

**Comment by OR13** [comment]
This issue should be closed.

**Comment by msporny** [comment]
We discussed this on the 2021-11-16. @OR13 reported in that a test has been added in PR #113 to address this issue. No further action needed. Closing.
